apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-alpha
  description: Team Alpha is responsible for the core platform services.
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: team-alpha@example.com
    picture: https://api.dicebear.com/7.x/identicon/svg?seed=Fluffy&backgroundType=solid,gradientLinear&backgroundColor=ffd5dc,b6e3f4
  parent: platformengineering
  # parent: backstage
  children: []
---
# these are copied from the backstage example org
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: amelia.park
spec:
  profile:
    displayName: Amelia Park
    email: amelia-park@example.com
    picture: https://api.dicebear.com/7.x/avataaars/svg?seed=Gizmo&backgroundColor=transparent
  memberOf: [team-alpha]
